# Generated by Django 6.0.3 on 2026-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
