# Generated by Django 6.0.3 on 2026-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
