# Generated by Django 6.0.3 on 2026-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
